spring:
  #解决swagger-ui.html 404问题
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/whm/*/mapper/*Mapper.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    call-setters-on-nulls: true
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  sql-log:
    enable: true
#日志配置
logging:
  level:
    com.whm.content.mapper: debug